jvmapp:
  build: .
  dockerfile: Dockerfile-jvmapp
  container_name: jvmapp
  environment:
    JMX_HOST: jvmapp
    JMX_PORT: 4000
  ports:
    - "4000:4000"

jmxtrans-docker:
  build: .
  dockerfile: Dockerfile-jmxtrans-image
  container_name: jmxtrans
  environment:
    JMX_HOST: jvmapp
    JMX_PORT: 4000
    HEAP_SIZE: 1024
    JAVA_OPTS: "-Djava.awt.headless=true -Djava.net.preferIPv4Stack=true"
    JMXTRANS_OPTS: "-Djmxtrans.log.level=info"
    SECONDS_BETWEEN_RUNS: 10
    INFLUXDB_PORT: 8086
    INFLUXDB_HOST: influxdb
    INFLUXDB_USER: admin
    INFLUXDB_PASSWD: admin
  links:
    - jvmapp
    - influxdb

influxdb:
  image: influxdb
  container_name: influxdb
  environment:
    INFLUXDB_ADMIN_USER: admin
    INFLUXDB_ADMIN_PASSWORD: admin
    INFLUXDB_HTTP_AUTH_ENABLED: "true"
    INFLUXDB_DB: "jmxdb"
  ports:
    - "8086:8086"

grafana:
  image: grafana/grafana
  container_name: grafana
  ports:
    - "80:3000"
